
(def-suite gio-content-type :in gio-suite)
(in-suite gio-content-type)

;;;   g_content_type_equals
;;;   g_content_type_is_a
;;;   g_content_type_is_unknown

;;;   g_content_type_get_description

(test g-content-type-get-description
  (is (equal '("CGM-Datei" "WebM-Video" "XPInstall-Installermodul" "DTSHD-Audio"
 "Linux-PSF-Konsolenschrift (gzip-komprimiert)" "LibreOffice Zeichnung"
 "JavaFX-Video" "Anjuta IDE Project Template" "Haansoft-Hangul-Dokumentvorlage"
 "Matroska-Video" "TeX-Schrift" "Haansoft-Hangul-Dokument" "ODC-Vorlage"
 "Comic-Book-Archiv" "StuffIt-Archiv" "OpenDocument Zeichnung (Flaches XML)"
 "AbiWord-Dokument" "Comic-Book-Archiv" "SGML-Dokument" "Comic-Book-Archiv"
 "WWF-Dokument" "SubViewer-Untertitel" "Flash-Video"
 "Angereichertes Textdokument" "Sieve-E-Mail-Filterskript" "RTF-Dokument"
 "ATK-Inset" "Liste widerrufener Zertifikate" "SystemVerilog-Quellcode"
 "LibreOffice Textdokumentvorlage" "SMAF-Audio" "SX/Xspread-Tabelle"
 "GSM-06.10-Audio" "Tar-Archiv (komprimiert)" "SPSS portable Datendatei"
 "Olympus-ORF-Rohbild" "OpenDocument Zeichnungsdokumentvorlage" "FLAC-Audio"
 "E-Mail-Nachrichtenfragment" "Isolierte OpenPGP-Signatur" "Scribus-Dokument"
 "WML-Dokument" "RTF-Textdokument" "Shell-Skript" "txt2tags-Dokument"
 "RAR-Archiv" "Lilypond-Notenblatt" "Photoshop-Bild" "Java-Bytecode"
 "RIFF-Audio" "Übersetzte Meldungen (maschinenlesbar)" "Haskell-Quelltext"
 "X11-Zeiger" "Wissenschaftlicher Graphite-Graph" "Animierter Windows-Cursor"
 "Dreamcast-ROM" "MathML-Dokument" "Einhängepunkt" "Audio-DVD"
 "StarChart-Diagramm" "WRI-Dokument" "Zoo-Archiv" "VRML-Dokument"
 "Komprimiertes SVG-Bild" "PNM-Bild" "MacOS-X-Symbol"
 "Windows-Media-Streamingbeschreibung" "WMF-Bild" "Comic-Book-Archiv"
 "SMIL-Dokument" "PDF-Dokument (bzip-komprimiert)" "XFig-Bild"
 "Quicken-Dokument" "Go-Quellcode" "Super-NES-ROM"
 "Portables Audio-Wiedergabegerät" "XML-Dokument-Entitäten" "LZO-Archiv"
 "FPX-Bild" "NFO-Dokument" "COBOL-Quelldatei" "Plucker-Dokument"
 "Webanwendungscache-Manifest" "V-Schrift" "BitTorrent-Seed-Datei"
 "UNIX Software" "Microsoft-Document-Imaging-Bildformat" "WebM-Audio"
 "Kivio-Flussdiagramm" "»Pathetic Writer«-Dokument"
 "Tar-Archiv (LZO-komprimiert)" "KML geographische komprimierte Daten"
 "Microsoft PowerPoint Präsentationsvorlage" "Adobe-FrameMaker-MIF-Dokument"
 "Nachrichtensammlung" "Video-DVD" "Apple-Datenträgerabbild" "ACE-Archiv"
 "LIBGRX-Schrift" "MacPaint-Bitmap-Datei" "Sony-SRF-Rohbild"
 "Nachrichtenkatalog" "OCL-Datei" "ODI-Bild" "E-Mail-Zustellungsbericht"
 "PlanPerfect-Tabelle" "Verweis auf entfernte Datei" "T602-Dokument"
 "TIFF-Bild" "Socket" "Kodak-KDC-Rohbild" "Excel Add-in" "XMF-Audio"
 "Annodex-Audio" "Eiffel-Quelltext" "Pascal-Quelltext"
 "PGP/MIME-verschlüsselter Nachrichtenkopf" "Shockwave-Flash-Datei" "Unbekannt"
 "MPEG-Video" "Makefile" "OpenDocument Text" "eMusic-Download-Paket"
 "WavPack-Audio" "Tar-Archiv (bzip-komprimiert)" "RealAudio-Dokument"
 "iptables-Konfigurationsdatei" "CD-Inhaltsverzeichnis"
 "Datenstrom (Server-Push)" "ASF-Video" "LibreOffice Zeichnungsvorlage"
 "VHDL-Quellcode" "EPS-Bild" "KFormula-Formel" "X-Window-Bild"
 "LibreOffice Extension" "Microsoft-Symbol" "LZMA-Archiv" "WBMP-Bild"
 "7zip-Archiv" "TrueAudio-Audio" "XPM-Bild" "Sony-SR2-Rohbild"
 "Signierte Nachricht" "RealTimeSync configuration file" "Blu-ray-Videoscheibe"
 "Musepack-Audio" "Scala-Quellcode" "Unterschiede zwischen Dateien"
 "Microsoft Excel Arbeitsblatt" "PAK-Archiv" "Ogg-Theora-Video"
 "Applix-Graphics-Bild" "Game-Boy-Advance-ROM" "Office-Zeichnung"
 "Anjuta IDE Project" "SystemVerilog-Header" "VOC-Audio" "Glade-Projekt"
 "KSysV-Init-Paket" "ANIM-Animation" "Speex-Audio"
 "Word-Dokument mit aktivierten Makros" "XSLT-Stylesheet" "XMI-Datei"
 "WMLScript-Programm" "OpenDocument Formel" "StarWriter-Dokument"
 "RPM-Spezifikationsdatei" "Bild-CD" "Dateibasiertes Kexi-Datenbankprojekt"
 "Dateibasiertes Kexi-Datenbankprojekt" "PPM-Bild" "LHZ-Archiv"
 "Internet-Verweis" "ODF-Vorlage" "Windows-Media-Audio" "Mathematica-Dokument"
 "JNLP-Datei" "MXF-Video" "FreeFileSync database file"
 "Microsoft Excel Arbeitsblattsvorlage" "PGN-Schachspielnotation"
 "Ustar-Archiv" "Zeichenorientiertes Gerät" "README-Dokument" "C++-Quelltext"
 "ISI-Video" "»Scream Tracker«-Audio" "Apport crash file" "FLTK-Fluid-Datei"
 "PKCS#10-Zertifikatanfrage" "Erlang-Quelltext" "LHA-Archiv"
 "TriG-RDF-Dokument" "WordPerfect/DrawPerfect-Bild" "Speedo-Schrift"
 "Ressourcenort" "MHTML-Web-Archiv" "PBM-Bild" "Blockorientiertes Gerät"
 "Android-Paket" "LDIF-Adressbuch" "YAML-Dokument" "Adobe-FrameMaker-Dokument"
 "Microsoft-Works-Dokument" "OCaml-Quelltext" "KChart-Diagramm" "SIS-Paket"
 "Microsoft PowerPoint Präsentationsvorlage" "AR-Archiv" "Matroska-Audio"
 "Bzip-Archiv" "NullSoft-Video" "Quelltext-RPM-Paket" "Annodex-Video"
 "Adobe-Schriftmetriken" "MP3-Audio" "Enlightenment-Thema" "Nikon-NEF-Rohbild"
 "BDF-Schrift" "C#-Quelltext" "EMF-Bild" "M4-Makro" "Vivo-Video"
 "application/x-note-Typ" "DTD-Datei" "OpenDocument Präsentation (Flaches XML)"
 "SunOS-News-Schrift" "QuickTime-Metalink-Wiedergabeliste" "Lzip-Archiv"
 "PCD-Bild" "SPSS-Datendatei" "Objective-C-Quelltext"
 "OpenRaster-Archivierungsbild" "DTS-Audio"
 "TeX-DVI-Dokument (bzip-komprimiert)" "JPEG-2000-Bild" "MPSub-Untertitel"
 "Nautilus-Verknüpfung" "Siag-Tabelle" "Tar-Archiv (lrzip-komprimiert)"
 "3GPP2-Multimediadatei" "WebVTT-Untertitel" "Sun-Rasterbild"
 "Sony-ARW-Rohbild" "DICOM-Bild" "»Lotus AmiPro«-Dokument" "Ada-Quelltext"
 "Scream-Tracker-3-Audio" "TeX-DVI-Dokument" "Gnuplot-Dokument" "WOFF-Schrift"
 "XBM-Bild" "PostScript-Dokument (gzip-komprimiert)" "Digitale Fotos"
 "Audio-CD" "Autorendanksagung" "Ogg-Speex-Audio" "HTML-Dokument" "GIMP-Bild"
 "AportisDoc-Dokument" "PEF-Programm" "StarImpress-Präsentation"
 "Verschlüsselte Nachricht" "Microsoft Word Dokument"
 "OpenDocument Präsentationsdokumentvorlage" "Gemeinsame libtool-Bibliothek"
 "WAIS-Quelltext" "DSSSL-Dokument" "Minolta-MRW-Rohbild" "Markaby-Skript"
 "MPEG-Video (Datenstrom)" "BibTeX-Dokument" "GNUnet-Suchdatei" "Shell-Archiv"
 "HomeBank File" "PKCS#7-Nachricht oder -Zertifikat" "SSA-Untertitel"
 "Java JCE-Schlüsselbund" "Adobe-FrameMaker-Schrift" "FLIC-Animation"
 "GNU-Mail-Nachricht" "PCL-Datei" "Word-Dokumentvorlage mit aktivierten Makros"
 "PCF-Schrift" "Karbon14-Zeichnung" "Vala-Quelltext" "OGM-Video" "G3-Faxbild"
 "Scheme-Quelltext" "OpenDocument Präsentation" "Hilfeseite"
 "Qt-Designer-Datei" "KIllustrator-Zeichnung"
 "Windows-Imaging-Format-Datenträgerabbild" "CD-Roh-Abbild"
 "CPIO-Archiv (gzip-komprimiert)" "C++-Header" "Nintendo64-ROM" "SQL-Befehle"
 "AIFF/Amiga/Mac-Audio" "»Impulse Tracker«-Audio" "TNEF-Nachricht"
 "SV4-CPIO-Archiv" "CD-Abbild-Cuesheet"
 "Kexi-Einstellungen für Verbindung zum Datenbankserver" "E-Mail-Kopfzeilen"
 "PkiPath-Zertifikatspfad" "Microsoft Excel Arbeitsblatt" "AIFC-Audio"
 "PDF-Dokument (gzip-komprimiert)" "Cisco-VPN-Einstellungen"
 "AmazonMP3-Download-Datei" "PowerPoint Add-in" "GTK+ Builder"
 "Troff-MS-Eingabedokument" "Emacs-Lisp-Quelltext" "Java-Quelltext"
 "Elektronisches Buch" "TeXInfo-Dokument" "JavaScript-Programm" "GML-Dokument"
 "Troff-MM-Eingabedokument" "FITS-Dokument" "CHM-Dokument"
 "PDF-Dokument (XZ-komprimiert)" "SAMI-Untertitel" "Troff-ME-Eingabedokument"
 "»Applix Spreadsheets«-Tabelle" "TeX-Schriftmetriken" "PSFlib-Audiobibliothek"
 "Microsoft PowerPoint Präsentation" "Quattro-Pro-Tabelle" "Modelica-Modell"
 "Shorten-Audio" "RELAX NG XML-Schema" "BCPIO-Dokument" "SubRip-Untertitel"
 "CCMX-Farbverbesserungsdatei" "E-Mail-Systembericht" "Corel-Draw-Zeichnung"
 "Python-Skript" "Panasonic raw2-Bild" "Genesis-ROM"
 "SDP-Multicast-Datenstromdatei" "JBuilder-Projekt"
 "LibreOffice Präsentationsvorlage" "TGA-Bild" "LightWave-Szene" "DIB-Bild"
 "DV-Video" "HTTP Live-Streaming-Wiedergabeliste" "LightWave-Objekt"
 "Microsoft-ASX-Wiedergabeliste" "PSF-Audio" "C-Shell-Skript" "AWK-Skript"
 "KML geographische Daten" "PowerPoint-Präsentation mit aktivierten Makros"
 "Leere CD" "WavPack-Audiokorrekturdatei" "Commodore-64-Audio"
 "Gepackte Schriftdatei" "PKCS#8 Geheimer Schlüssel"
 "Tar-Archiv (gzip-komprimiert)" "Microsoft Visio-Dokument"
 "iRiver-Wiedergabeliste" "IDL-Dokument" "PCM-Audio"
 "SPKAC Certificate Request" "IFF-Datei" "Linux-PSF-Konsolenschrift"
 "Troff-Dokument" "GnuCash-Finanzdaten" "RDF-Datei" "MPEG-4-Video"
 "MNG-Animation" "DOS/Windows-Programm" "Ogg-Vorbis-Audio"
 "Tabellenkalkulations-Austauschdokument" "Daten zu Programmabsturz"
 "Microsoft PowerPoint Präsentation" "EPS-Bild (bzip-komprimiert)"
 "Excel-Tabelle mit aktivierten Makros" "Windows-Software"
 "Leeres Blu-Ray-Medium" "Macintosh-Datei (BinHex-kodiert)"
 "Microsoft-Cabinet-Archiv" "Microsoft Word Dokument"
 "Tar-Archiv (LZMA-komprimiert)" "Pocket-Word-Dokument" "NewzBin-Usenet-Index"
 "KWord-Dokument" "Verilog-Quellcode" "X-Motif-UIL-Tabelle" "PGM-Bild"
 "PS-Dokument" "SGI-Bild" "Video-CD" "Lrzip-Archiv"
 "Excel 2007-Tabelle (binär)" "Sega-Master-System/Game-Gear-ROM"
 "TrueType-XML-Schrift" "Markdown-Dokument" "Dia-Diagramm"
 "SPKAC Certificate Request in OpenSSL format" "RealPix-Dokument"
 "FreeFileSync configuration file" "Microsoft Word Dokument" "CCITT-G3-Fax"
 "D-Quelltext" "StarMath-Formel"
 "PowerPoint-Präsentation mit aktivierten Makros" "TrueType-Schrift"
 "MPEG-4-Audio" "MP2-Audio" "HPGL-Datei" "Applix-Words-Dokument" "Thema"
 "KPovModeler-Szene" "Skencil-Dokument" "XUL-Oberflächendokument"
 "SGF-Aufzeichnung" "Übersetzungsdatei" "Java-Archiv" "RPM-Paket"
 "Lotus Word Pro" "Gzip-Archiv" "Monkey's-Audio" "Brasero-Projektdatei"
 "WAV-Audio" "Windows-Registry-Auszug" "KSpread-Tabelle"
 "KPresenter-Präsentation" "Setext-Dokument"
 "PKCS#12 Personal Key and Certificates in PEM format"
 "Excel-Tabellenvorlage mit aktivierten Makros" "AMR-Audio" "Software"
 "Profiler-Ergebnisse" "Perl-Skript" "GMC-Verweis" "ODB-Datenbank"
 "E-Book-Leser" "Netzwerk-Paketmitschnitt" "CSV-Dokument"
 "Themenpaket für Microsoft Windows" "Citrix-ICA-Einstellungsdatei"
 "CSS-Stilvorlage" "ASP-Seite" "RGB-Bild" "OLE2-Verbunddokumentenspeicher"
 "PostScript-Dokument (bzip-komprimiert)" "QtiPlot-Dokument" "Ogg-Video"
 "XLIFF-Übersetzung" "WPL-Wiedergabeliste" "Pack200-Java-Archiv"
 "Metalink-Datei" "DirectDraw-Oberfläche" "Canon-CRW-Rohbild"
 "Kodak-DCR-Rohbild" "Leeres Dokument" "Digitales Rohbild" "DPX-Bild"
 "OpenDocument Textdokumentvorlage" "Annodex-Wechselformat"
 "Einfaches Textdokument" "PowerPoint 2007-Folie" "AVI-Video" "Stampede-Paket"
 "HDF-Dokument" "RealMedia-Metadatei" "MP3-Audio (Stream)" "Metalink-Datei"
 "XBEL-Lesezeichen" "ARJ-Archiv" "»Macintosh Quickdraw/PICT«-Zeichnung"
 "PGP-Schlüssel" "Ogg-Multimediadatei" "TeX-DVI-Dokument (gzip-komprimiert)"
 "Ruby-Skript" "ARC-Archiv" "Sicherungsdatei" "WordPerfect-Dokument"
 "Blender-Szene" "OPML-Nachrichtenquelle" "Microsoft Word Dokument"
 "Fuji-RAF-Rohbild" "Ogg-Audio" "IEF-Bild" "Komprimiertes GIMP-Bild"
 "Pentax-PEF-Rohbild" "GIF-Bild" "QuickTime-Video" "uuencoded-Datei"
 "LyX-Dokument" "Programm" "Qt-Auszeichnungssprachendatei"
 "PKCS#7 Message and Certificates in PEM format" "Änderungsprotokoll"
 "Mup-Veröffentlichung" "Macintosh-MacBinary-Datei" "PDF-Dokument" "JPEG-Bild"
 "OpenDocument Text (Flaches XML)" "Gnumeric-Tabelle" "Canon-CR2-Rohbild"
 "Usenet-News-Nachricht" "»Game Boy«-ROM" "LHS-Quelltext"
 "Postscript-Typ-1-Schrift" "ECMAScript-Programm" "RealText-Dokument"
 "Microsoft Word Dokumentvorlage" "Abgelehnter Patch" "CMake-Quelltext"
 "Troff-Dokument (mit man-Seitenmakros)" "Desktop-Konfigurationsdatei"
 "PowerPoint-2007-Präsentation" "Atom-Nachrichtenquelle" "DocBook-Dokument"
 "Isolierte S/MIME-Signatur" "Gemeinsame Bibliothek" "WinHelp-Hilfedatei"
 "Openssl PEM format" "MATLAB-Skript/-Funktion" "PKCS#12-Zertifikatspaket"
 "SGI-Video" "MPEG-4-Hörbuch" "TeX-Dokument" "LibreOffice Tabellenvorlage"
 "Matroska-Datenstrom" "OpenDocument Globaldokument" "FictionBook-Dokument"
 "Autorenliste" "JAD-Dokument" "MicroDVD-Untertitel" "HD-DVD-Videoscheibe"
 "CPIO-Archiv" "Kontour-Zeichnung" "JET-Datenbank" "LibreOffice Formel"
 "VCS/ICS-Kalender" "Egon-Animator-Animation" "Software sources list"
 "C-Quelltext" "PKCS#10 Certificate Request in PEM format" "RealVideo-Dokument"
 "MSX-ROM" "ODA-Dokument" "OOC-Quellcode" "Graphviz-DOT-Graph"
 "SV4-CPIO-Archiv (mit CRC)" "Super-Video-CD" "GNU-Oleo-Tabelle"
 "PKCS#8 Personal Key in PEM format" "OpenDocument Zeichnung" "Lua-Skript"
 "Google Video Pointer" "OpenDocument Tabellendokument" "MIDI-Audio"
 "CMU-Rasterbild" "PKCS#7-Nachricht oder -Zertifikat"
 "Macintosh-Datei (AppleDouble-kodiert)" "DXF-Vektorbild" "Pipe" "DOS-Schrift"
 "GEDCOM-Stammbaum" "NES-ROM" "ToutDoux-Dokument" "»Dolby Digital«-Audio"
 "Nintendo-DS-ROM" "DjVu-Bild" "Panasonic-Rohbild" "MPEG-2-Transportstrom"
 "»Lotus 1-2-3«-Tabelle" "LibreOffice Präsentation" "Allgemeine Schriftdatei"
 "StarDraw-Zeichnung" "StarCalc-Tabelle" "Installationsanleitung"
 "Mailbox-Datei" "AAC-Audio" "Objekt-Code" "XSPF-Wiedergabeliste"
 "Gespeicherte Suche" "Tcl-Skript" "LibreOffice Textdokument"
 "Unidata-NetCDF-Dokument" "Kodak-K25-Rohbild" "AutoCAD-Bild"
 "SQLite3-Datenbank" "SQLite2-Datenbank" "Mozilla-Lesezeichen"
 "Amiga-SoundTracker-Audio" "Python-Bytecode" "Windows Installationspaket"
 "RealMedia-Dokument" "»Adobe Illustrator«-Dokument"
 "LibreOffice Globaldokument" "ICC-Profil" "Alzip-Archiv" "XSL-FO-Datei"
 "OpenDocument Tabellendokument (Flaches XML)" "GTKtalog-Katalog"
 "Java-Schlüsselbund" "RSS-Zusammenfassung" "UNIX-komprimierte Datei"
 "Microsoft Word Dokumentvorlage" "Tar-Archiv (XZ-komprimiert)" "Zip-Archiv"
 "Lauflängenkodiertes Bitmap-Bild" "Word-Vorlage" "PCX-Bild" "XML-Dokument"
 "Verbunddokumente" "XZ-Archiv" "Leere HD-DVD" "Krita-Dokument"
 "Schnellzugriff zum Kexi-Projekt auf dem Datenbankserver"
 "3GPP-Multimediadatei" "Komprimiertes Tracker-Audio" "DCL-Skript"
 "Windows-BMP-Bild" "KWord-Dokument (verschlüsselt)" "ILBM-Bild"
 "FreeFileSync batch file" "Debian-Paket" "Ordner" "Übersetzungsvorlage"
 "EPS-Bild (gzip-komprimiert)" "Nachricht in mehreren Formaten" "Dia-Form"
 "Windows-Media-Video" "QuickTime-Bild" "Fortran-Quelltext" "Qt-MOC-Datei"
 "MP3-ShoutCast-Wiedergabeliste" "Managed Object Format"
 "Apple-optimierte PNG-Grafik" "OpenDocument Tabellendokumentvorlage"
 "3D-Studio-Bild" "Microsoft PowerPoint Präsentation"
 "Anjuta IDE Compressed Project Template" "iPod-Firmware" "OpenType-Schrift"
 "Ogg-FLAC-Audio" "Mobipocket E-Book" "Wavelet-Video"
 "Format zur Linear- und Ganzzahlenprogrammierung" "HTML-Dokumentvorlage"
 "StarMail-E-Mail" "Microsoft Excel Arbeitsblattsvorlage" "XPS-Dokument"
 "Private Key in PEM format" "Sigma-X3F-Rohbild" "EXR-Bild" "PNG-Bild"
 "JNG-Bild" "X.509 Certificate in PEM format" "Leere DVD"
 "Certificate Revocation List in PEM format" "Symbolische Verknüpfung"
 "Windows-Cursor" "C-Header" "IT 8.7 Farbkalibrierungsdatei" "Tar-Archiv"
 "Lizenzbedingungen" "AMR-WB-Audio" "ODC-Diagramm" "Parchive-Archiv"
 "PowerPoint-Präsentationsvorlage mit aktivierten Makros" "X.509-Zertifikat"
 "E-Mail-Nachricht" "TSV-Dokument" "UFRaw-Bildbeschreibungsdatei"
 "Handbuchseite (komprimiert)" "»FastTracker II«-Audio" "Java-Klasse"
 "»Palm OS«-Datenbank" "Scream-Tracker-Instrument" "Anwendungsprotokoll"
 "KeePass 2 Datenbank" "Microsoft Excel Arbeitsblatt" "iMelody-Klingelton"
 "PHP-Skript" "ULAW-Audio (Sun)" "SVG-Bild" "MiniPSF-Audio" "NIFF-Bild"
 "Elektronische Visitenkarte" "X.509-Zertifikat"
 "KSpread-Tabelle (verschlüsselt)" "OpenDocument Datenbank" "XMCD-CD-Datenbank"
 "MagicPoint-Präsentation" "Xbase-Dokument" "Microsoft Excel Arbeitsblatt"
 "GDBM-Datenbank" "PowerPoint-Folie mit aktivierten Makros"
 "Adobe Digitales Negativ" "XHTML-Seite" "TGIF-Dokument" "SISX-Paket"
 "Verbunddokument" "DAR-Archiv" "MRML-Wiedergabeliste" "LibreOffice Tabelle"
 "Kugar-Dokument" "E-Mail-Übertragungsbericht")
            (mapcar #'g-content-type-get-description
                    (g-content-types-get-registered)))))

;;;   g_content_type_get_mime_type

(test g-content-type-get-mime-type
  (is (equal '("image/cgm" "video/webm" "application/x-xpinstall" "audio/vnd.dts.hd"
 "application/x-gz-font-linux-psf" "application/vnd.sun.xml.draw"
 "video/x-javafx" "application/x-anjuta-project-template" "application/x-hwt"
 "video/x-matroska" "application/x-font-tex" "application/x-hwp"
 "application/vnd.oasis.opendocument.chart-template" "application/x-cbz"
 "application/x-stuffit" "application/vnd.oasis.opendocument.graphics-flat-xml"
 "application/x-abiword" "application/x-cbt" "text/sgml" "application/x-cbr"
 "application/x-wwf" "text/x-subviewer" "video/x-flv" "text/enriched"
 "application/sieve" "application/rtf" "application/andrew-inset"
 "application/pkix-crl" "text/x-svsrc"
 "application/vnd.sun.xml.writer.template" "application/x-smaf"
 "application/x-sc" "audio/x-gsm" "application/x-tarz" "application/x-spss-por"
 "image/x-olympus-orf" "application/vnd.oasis.opendocument.graphics-template"
 "audio/flac" "message/partial" "application/pgp-signature"
 "application/vnd.scribus" "text/vnd.wap.wml" "text/richtext"
 "application/x-shellscript" "text/x-txt2tags" "application/x-rar"
 "text/x-lilypond" "image/vnd.adobe.photoshop" "application/x-class-file"
 "audio/x-riff" "application/x-gettext-translation" "text/x-haskell"
 "image/x-xcursor" "application/x-graphite" "application/x-navi-animation"
 "application/x-dc-rom" "application/mathml+xml" "inode/mount-point"
 "x-content/audio-dvd" "application/vnd.stardivision.chart"
 "application/x-mswrite" "application/x-zoo" "model/vrml"
 "image/svg+xml-compressed" "image/x-portable-anymap" "image/x-icns"
 "application/x-netshow-channel" "image/x-wmf" "application/x-cb7"
 "application/smil" "application/x-bzpdf" "image/x-xfig" "application/x-qw"
 "text/x-go" "application/x-snes-rom" "x-content/audio-player"
 "application/xml-external-parsed-entity" "application/x-lzop" "image/x-fpx"
 "text/x-nfo" "text/x-cobol" "application/prs.plucker" "text/cache-manifest"
 "application/x-font-vfont" "application/x-bittorrent"
 "x-content/unix-software" "image/vnd.ms-modi" "audio/webm"
 "application/x-kivio" "application/x-pw" "application/x-tzo"
 "application/vnd.google-earth.kmz"
 "application/vnd.openxmlformats-officedocument.presentationml.template"
 "application/x-mif" "multipart/digest" "x-content/video-dvd"
 "application/x-apple-diskimage" "application/x-ace"
 "application/x-font-libgrx" "image/x-macpaint" "image/x-sony-srf"
 "text/vnd.trolltech.linguist" "text/x-ocl"
 "application/vnd.oasis.opendocument.image" "message/delivery-status"
 "application/x-planperfect" "message/external-body" "application/x-t602"
 "image/tiff" "inode/socket" "image/x-kodak-kdc"
 "application/vnd.ms-excel.addin.macroEnabled.12" "audio/x-xmf" "audio/annodex"
 "text/x-eiffel" "text/x-pascal" "application/pgp-encrypted"
 "application/x-shockwave-flash" "application/octet-stream" "video/mpeg"
 "text/x-makefile" "application/vnd.oasis.opendocument.text"
 "application/vnd.emusic-emusic_package" "audio/x-wavpack"
 "application/x-bzip-compressed-tar" "audio/vnd.rn-realaudio" "text/x-iptables"
 "application/x-cdrdao-toc" "multipart/x-mixed-replace" "video/x-ms-asf"
 "application/vnd.sun.xml.draw.template" "text/x-vhdl" "image/x-eps"
 "application/x-kformula" "image/x-xwindowdump"
 "application/vnd.openofficeorg.extension" "image/vnd.microsoft.icon"
 "application/x-lzma" "image/vnd.wap.wbmp" "application/x-7z-compressed"
 "audio/x-tta" "image/x-xpixmap" "image/x-sony-sr2" "multipart/signed"
 "application/x-freefilesync-real" "x-content/video-bluray" "audio/x-musepack"
 "text/x-scala" "text/x-patch" "application/vnd.ms-excel" "application/x-pak"
 "video/x-theora+ogg" "image/x-applix-graphics" "application/x-gba-rom"
 "image/x-msod" "application/x-anjuta" "text/x-svhdr" "audio/x-voc"
 "application/x-glade" "application/x-ksysv-package" "video/x-anim"
 "audio/x-speex" "application/vnd.ms-word.document.macroEnabled.12"
 "application/xslt+xml" "text/x-xmi" "text/vnd.wap.wmlscript"
 "application/vnd.oasis.opendocument.formula"
 "application/vnd.stardivision.writer" "text/x-rpm-spec"
 "x-content/image-picturecd" "application/x-kexiproject-sqlite3"
 "application/x-kexiproject-sqlite2" "image/x-portable-pixmap"
 "application/x-lhz" "application/x-mswinurl"
 "application/vnd.oasis.opendocument.formula-template" "audio/x-ms-wma"
 "application/mathematica" "application/x-java-jnlp-file" "application/mxf"
 "application/x-freefilesync-db"
 "application/vnd.openxmlformats-officedocument.spreadsheetml.template"
 "application/x-chess-pgn" "application/x-ustar" "inode/chardevice"
 "text/x-readme" "text/x-c++src" "video/isivideo" "audio/x-stm" "text/x-apport"
 "application/x-fluid" "application/pkcs10" "text/x-erlang" "application/x-lha"
 "application/x-trig" "application/x-wpg" "application/x-font-speedo"
 "text/x-uri" "application/x-mimearchive" "image/x-portable-bitmap"
 "inode/blockdevice" "application/vnd.android.package-archive" "text/x-ldif"
 "application/x-yaml" "application/x-frame" "application/vnd.ms-works"
 "text/x-ocaml" "application/x-kchart" "application/vnd.symbian.install"
 "application/vnd.ms-powerpoint.template.macroenabled.12"
 "application/x-archive" "audio/x-matroska" "application/x-bzip" "video/x-nsv"
 "application/x-source-rpm" "video/annodex" "application/x-font-afm"
 "audio/mpeg" "application/x-e-theme" "image/x-nikon-nef"
 "application/x-font-bdf" "text/x-csharp" "image/x-emf" "application/x-m4"
 "video/vivo" "application/x-note" "application/xml-dtd"
 "application/vnd.oasis.opendocument.presentation-flat-xml"
 "application/x-font-sunos-news" "application/x-quicktime-media-link"
 "application/x-lzip" "image/x-photo-cd" "application/x-spss-sav"
 "text/x-objcsrc" "image/openraster" "audio/vnd.dts" "application/x-bzdvi"
 "image/jp2" "text/x-mpsub" "application/x-nautilus-link" "application/x-siag"
 "application/x-lrzip-compressed-tar" "video/3gpp2" "text/vtt"
 "image/x-sun-raster" "image/x-sony-arw" "application/dicom"
 "application/x-amipro" "text/x-adasrc" "audio/x-s3m" "application/x-dvi"
 "application/x-gnuplot" "application/font-woff" "image/x-xbitmap"
 "application/x-gzpostscript" "x-content/image-dcf" "x-content/audio-cdda"
 "text/x-credits" "audio/x-speex+ogg" "text/html" "image/x-xcf"
 "application/x-aportisdoc" "application/x-pef-executable"
 "application/vnd.stardivision.impress" "multipart/encrypted"
 "application/vnd.ms-word"
 "application/vnd.oasis.opendocument.presentation-template"
 "application/x-shared-library-la" "application/x-wais-source" "text/x-dsl"
 "image/x-minolta-mrw" "application/x-markaby" "video/vnd.mpegurl"
 "text/x-bibtex" "application/gnunet-directory" "application/x-shar"
 "application/x-homebank" "application/x-pkcs7-certificates" "text/x-ssa"
 "application/x-java-jce-keystore" "application/x-font-framemaker"
 "video/x-flic" "message/x-gnu-rmail" "application/vnd.hp-pcl"
 "application/vnd.ms-word.template.macroEnabled.12" "application/x-font-pcf"
 "application/x-karbon" "text/x-vala" "video/x-ogm+ogg" "image/g3fax"
 "text/x-scheme" "application/vnd.oasis.opendocument.presentation" "text/htmlh"
 "application/x-designer" "application/x-killustrator" "application/x-ms-wim"
 "application/x-cd-image" "application/x-cpio-compressed" "text/x-c++hdr"
 "application/x-n64-rom" "text/x-sql" "audio/x-aiff" "audio/x-it"
 "application/vnd.ms-tnef" "application/x-sv4cpio" "application/x-cue"
 "application/x-kexi-connectiondata" "text/rfc822-headers"
 "application/pkix-pkipath"
 "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
 "audio/x-aifc" "application/x-gzpdf" "application/x-cisco-vpn-settings"
 "audio/x-amzxml" "application/vnd.ms-powerpoint.addin.macroEnabled.12"
 "application/x-gtk-builder" "text/x-troff-ms" "text/x-emacs-lisp"
 "text/x-java" "application/epub+zip" "text/x-texinfo" "application/javascript"
 "application/gml+xml" "text/x-troff-mm" "image/fits"
 "application/vnd.ms-htmlhelp" "application/x-xzpdf" "application/x-sami"
 "text/x-troff-me" "application/x-applix-spreadsheet"
 "application/x-font-tex-tfm" "audio/x-psflib" "application/vnd.ms-powerpoint"
 "application/x-quattropro" "text/x-modelica" "application/x-shorten"
 "application/relax-ng-compact-syntax" "application/x-bcpio"
 "application/x-subrip" "application/x-ccmx" "multipart/report"
 "application/vnd.corel-draw" "text/x-python" "image/x-panasonic-raw2"
 "application/x-genesis-rom" "application/sdp" "application/x-jbuilder-project"
 "application/vnd.sun.xml.impress.template" "image/x-tga" "image/x-lws"
 "image/x-dib" "video/dv" "application/vnd.apple.mpegurl" "image/x-lwo"
 "audio/x-ms-asx" "audio/x-psf" "application/x-csh" "application/x-awk"
 "application/vnd.google-earth.kml+xml"
 "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" "x-content/blank-cd"
 "audio/x-wavpack-correction" "audio/prs.sid" "application/x-tex-pk"
 "application/pkcs8" "application/x-compressed-tar" "application/vnd.visio"
 "audio/x-iriver-pla" "text/x-idl" "audio/x-adpcm" "application/x-spkac"
 "application/x-iff" "application/x-font-linux-psf" "text/troff"
 "application/x-gnucash" "application/rdf+xml" "video/mp4" "video/x-mng"
 "application/x-ms-dos-executable" "audio/x-vorbis+ogg" "text/spreadsheet"
 "application/x-core"
 "application/vnd.openxmlformats-officedocument.presentationml.presentation"
 "image/x-bzeps" "application/vnd.ms-excel.sheet.macroEnabled.12"
 "x-content/win32-software" "x-content/blank-bd" "application/mac-binhex40"
 "application/vnd.ms-cab-compressed" "application/msword"
 "application/x-lzma-compressed-tar" "application/x-pocket-word"
 "application/x-nzb" "application/x-kword" "text/x-verilog" "text/x-uil"
 "image/x-portable-graymap" "application/postscript" "image/x-sgi"
 "x-content/video-vcd" "application/x-lrzip"
 "application/vnd.ms-excel.sheet.binary.macroEnabled.12"
 "application/x-sms-rom" "application/x-font-ttx" "text/x-markdown"
 "application/x-dia-diagram" "application/x-spkac+base64"
 "image/vnd.rn-realpix" "application/x-freefilesync-ffs"
 "application/vnd.ms-word.document.macroenabled.12" "image/fax-g3"
 "text/x-dsrc" "application/vnd.stardivision.math"
 "application/vnd.ms-powerpoint.presentation.macroEnabled.12"
 "application/x-font-ttf" "audio/mp4" "audio/mp2" "application/vnd.hp-hpgl"
 "application/x-applix-word" "application/x-theme" "application/x-kpovmodeler"
 "image/x-skencil" "application/vnd.mozilla.xul+xml" "application/x-go-sgf"
 "text/x-gettext-translation" "application/x-java-archive" "application/x-rpm"
 "application/vnd.lotus-wordpro" "application/gzip" "audio/x-ape"
 "application/x-brasero" "audio/x-wav" "text/x-ms-regedit"
 "application/x-kspread" "application/x-kpresenter" "text/x-setext"
 "application/pkcs12+pem" "application/vnd.ms-excel.template.macroEnabled.12"
 "audio/AMR" "x-content/software" "application/x-profile" "application/x-perl"
 "application/x-gmc-link" "application/vnd.oasis.opendocument.database"
 "x-content/ebook-reader" "application/vnd.tcpdump.pcap" "text/csv"
 "application/x-windows-themepack" "application/x-ica" "text/css"
 "application/x-asp" "image/x-rgb" "application/x-ole-storage"
 "application/x-bzpostscript" "application/x-qtiplot" "video/ogg"
 "application/x-xliff" "application/vnd.ms-wpl" "application/x-java-pack200"
 "application/metalink+xml" "image/x-dds" "image/x-canon-crw"
 "image/x-kodak-dcr" "application/x-zerosize" "image/x-dcraw" "image/dpx"
 "application/vnd.oasis.opendocument.text-template" "application/annodex"
 "text/plain"
 "application/vnd.openxmlformats-officedocument.presentationml.slide"
 "video/x-msvideo" "application/x-slp" "application/x-hdf" "application/ram"
 "audio/x-mpegurl" "application/metalink4+xml" "application/x-xbel"
 "application/x-arj" "image/x-pict" "application/pgp-keys" "application/ogg"
 "application/x-gzdvi" "application/x-ruby" "application/x-arc"
 "application/x-trash" "application/vnd.wordperfect" "application/x-blender"
 "text/x-opml+xml"
 "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
 "image/x-fuji-raf" "audio/ogg" "image/ief" "image/x-compressed-xcf"
 "image/x-pentax-pef" "image/gif" "video/quicktime" "text/x-uuencode"
 "application/x-lyx" "application/x-executable" "text/x-qml"
 "application/pkcs7-mime+pem" "text/x-changelog" "text/x-mup"
 "application/x-macbinary" "application/pdf" "image/jpeg"
 "application/vnd.oasis.opendocument.text-flat-xml" "application/x-gnumeric"
 "image/x-canon-cr2" "message/news" "application/x-gameboy-rom"
 "text/x-literate-haskell" "application/x-font-type1" "application/ecmascript"
 "text/vnd.rn-realtext" "application/vnd.ms-word.template.macroenabled.12"
 "text/x-reject" "text/x-cmake" "application/x-troff-man"
 "application/x-desktop"
 "application/vnd.openxmlformats-officedocument.presentationml.slideshow"
 "application/atom+xml" "application/x-docbook+xml"
 "application/pkcs7-signature" "application/x-sharedlib" "application/winhlp"
 "application/x-pem-file" "text/x-matlab" "application/x-pkcs12"
 "video/x-sgi-movie" "audio/x-m4b" "text/x-tex"
 "application/vnd.sun.xml.calc.template" "application/x-matroska"
 "application/vnd.oasis.opendocument.text-master"
 "application/x-fictionbook+xml" "text/x-authors"
 "text/vnd.sun.j2me.app-descriptor" "text/x-microdvd" "x-content/video-hddvd"
 "application/x-cpio" "application/x-kontour" "application/vnd.ms-access"
 "application/vnd.sun.xml.math" "text/calendar" "application/x-egon"
 "text/x-apt-sources-list" "text/x-csrc" "application/pkcs10+pem"
 "video/vnd.rn-realvideo" "application/x-msx-rom" "application/oda"
 "text/x-ooc" "text/vnd.graphviz" "application/x-sv4crc" "x-content/video-svcd"
 "application/x-oleo" "application/pkcs8+pem"
 "application/vnd.oasis.opendocument.graphics" "text/x-lua"
 "text/x-google-video-pointer" "application/vnd.oasis.opendocument.spreadsheet"
 "audio/midi" "image/x-cmu-raster" "application/pkcs7-mime"
 "multipart/appledouble" "image/vnd.dxf" "inode/fifo" "application/x-font-dos"
 "application/x-gedcom" "application/x-nes-rom" "application/x-toutdoux"
 "audio/ac3" "application/x-nintendo-ds-rom" "image/vnd.djvu"
 "image/x-panasonic-raw" "video/mp2t" "application/vnd.lotus-1-2-3"
 "application/vnd.sun.xml.impress" "application/x-tex-gf"
 "application/vnd.stardivision.draw" "application/vnd.stardivision.calc"
 "text/x-install" "application/mbox" "audio/aac" "application/x-object"
 "application/xspf+xml" "application/x-gnome-saved-search" "text/x-tcl"
 "application/vnd.sun.xml.writer" "application/x-netcdf" "image/x-kodak-k25"
 "image/vnd.dwg" "application/x-sqlite3" "application/x-sqlite2"
 "application/x-mozilla-bookmarks" "audio/x-mod"
 "application/x-python-bytecode" "application/x-msi"
 "application/vnd.rn-realmedia" "application/illustrator"
 "application/vnd.sun.xml.writer.global" "application/vnd.iccprofile"
 "application/x-alz" "text/x-xslfo"
 "application/vnd.oasis.opendocument.spreadsheet-flat-xml"
 "application/x-gtktalog" "application/x-java-keystore" "application/rss+xml"
 "application/x-compress"
 "application/vnd.openxmlformats-officedocument.wordprocessingml.template"
 "application/x-xz-compressed-tar" "application/zip" "image/rle"
 "application/msword-template" "image/x-pcx" "application/xml"
 "multipart/mixed" "application/x-xz" "x-content/blank-hddvd"
 "application/x-krita" "application/x-kexiproject-shortcut" "video/3gpp"
 "audio/x-mo3" "text/x-dcl" "image/bmp" "application/x-kword-crypt"
 "image/x-ilbm" "application/x-freefilesync-batch" "application/x-deb"
 "inode/directory" "text/x-gettext-translation-template" "image/x-gzeps"
 "multipart/alternative" "application/x-dia-shape" "video/x-ms-wmv"
 "image/x-quicktime" "text/x-fortran" "text/x-moc" "audio/x-scpls" "text/x-mof"
 "image/x-apple-ios-png"
 "application/vnd.oasis.opendocument.spreadsheet-template" "image/x-3ds"
 "application/vnd.ms-powerpoint.presentation.macroenabled.12"
 "application/x-anjuta-compressed-project-template"
 "application/x-ipod-firmware" "application/x-font-otf" "audio/x-flac+ogg"
 "application/x-mobipocket-ebook" "video/wavelet" "application/x-mps"
 "application/vnd.oasis.opendocument.text-web"
 "application/vnd.stardivision.mail"
 "application/vnd.ms-excel.template.macroenabled.12" "application/oxps"
 "application/x-pem-key" "image/x-sigma-x3f" "image/x-exr" "image/png"
 "image/x-jng" "application/pkix-cert+pem" "x-content/blank-dvd"
 "application/pkix-crl+pem" "inode/symlink" "image/x-win-bitmap" "text/x-chdr"
 "application/x-it87" "application/x-tar" "text/x-copying" "audio/AMR-WB"
 "application/vnd.oasis.opendocument.chart" "application/x-par2"
 "application/vnd.ms-powerpoint.template.macroEnabled.12"
 "application/x-x509-ca-cert" "message/rfc822" "text/tab-separated-values"
 "application/x-ufraw" "application/x-troff-man-compressed" "audio/x-xm"
 "application/x-java" "application/vnd.palm" "audio/x-xi" "text/x-log"
 "application/x-keepass2" "application/vnd.ms-excel.sheet.macroenabled.12"
 "text/x-iMelody" "application/x-php" "audio/basic" "image/svg+xml"
 "audio/x-minipsf" "image/x-niff" "text/vcard" "application/pkix-cert"
 "application/x-kspread-crypt" "application/vnd.sun.xml.base" "text/xmcd"
 "application/x-magicpoint" "application/x-dbf"
 "application/vnd.ms-excel.sheet.binary.macroenabled.12" "application/x-gdbm"
 "application/vnd.ms-powerpoint.slide.macroEnabled.12" "image/x-adobe-dng"
 "application/xhtml+xml" "application/x-tgif" "x-epoc/x-sisx-app"
 "multipart/related" "application/x-dar" "text/x-mrml"
 "application/vnd.sun.xml.calc" "application/x-kugar"
 "message/disposition-notification")
             (mapcar #'g-content-type-get-mime-type
                     (g-content-types-get-registered)))))

;;;   g_content_type_get_icon

(test g-content-type-get-icon
  (is (eq 'g-themed-icon
          (type-of (g-content-type-get-icon "image/cgm")))))

;;;   g_content_type_get_symbolic_icon

(test g-content-type-get-symbolic-icon
  (is (eq 'g-themed-icon
          (type-of (g-content-type-get-symbolic-icon "image/cgm")))))

;;;   g_content_type_get_generic_icon_name

(test g-content-type-get-generic-icon-name
  (is (equal '("image-x-generic" "video-x-generic" "application-x-generic" "audio-x-generic"
 "font-x-generic" "image-x-generic" "video-x-generic" "application-x-generic"
 "x-office-document" "video-x-generic" "font-x-generic" "x-office-document"
 "x-office-spreadsheet" "x-office-document" "package-x-generic"
 "image-x-generic" "x-office-document" "x-office-document" "text-x-generic"
 "x-office-document" "x-office-document" "text-x-generic" "video-x-generic"
 "text-x-generic" "text-x-script" "x-office-document" "x-office-document"
 "application-x-generic" "text-x-generic" "x-office-document" "audio-x-generic"
 "x-office-spreadsheet" "audio-x-generic" "package-x-generic"
 "application-x-generic" "image-x-generic" "image-x-generic" "audio-x-generic"
 "text-x-generic" "text-x-generic" "application-x-generic" "text-x-generic"
 "text-x-generic" "text-x-script" "text-x-generic" "package-x-generic"
 "text-x-generic" "image-x-generic" "application-x-generic" "audio-x-generic"
 "application-x-generic" "text-x-generic" "image-x-generic" "x-office-document"
 "application-x-generic" "application-x-executable" "application-x-generic"
 "inode-x-generic" "x-content-x-generic" "x-office-spreadsheet"
 "x-office-document" "package-x-generic" "x-office-document" "image-x-generic"
 "image-x-generic" "image-x-generic" "video-x-generic" "image-x-generic"
 "x-office-document" "video-x-generic" "x-office-document" "image-x-generic"
 "x-office-spreadsheet" "text-x-generic" "application-x-executable"
 "x-content-x-generic" "text-html" "package-x-generic" "image-x-generic"
 "text-x-generic" "text-x-generic" "x-office-document" "text-x-generic"
 "font-x-generic" "application-x-generic" "x-content-x-generic"
 "image-x-generic" "audio-x-generic" "x-office-document" "x-office-document"
 "package-x-generic" "application-x-generic" "x-office-presentation"
 "application-x-generic" "multipart-x-generic" "x-content-x-generic"
 "application-x-generic" "package-x-generic" "font-x-generic" "image-x-generic"
 "image-x-generic" "text-x-generic" "text-x-generic" "image-x-generic"
 "text-x-generic" "x-office-spreadsheet" "text-x-generic" "x-office-document"
 "image-x-generic" "inode-x-generic" "image-x-generic" "x-office-spreadsheet"
 "audio-x-generic" "audio-x-generic" "text-x-generic" "text-x-generic"
 "text-x-generic" "video-x-generic" "application-x-generic" "video-x-generic"
 "text-x-generic" "x-office-document" "package-x-generic" "audio-x-generic"
 "package-x-generic" "audio-x-generic" "text-x-generic" "text-x-generic"
 "multipart-x-generic" "video-x-generic" "image-x-generic" "text-x-generic"
 "image-x-generic" "x-office-document" "image-x-generic" "x-office-document"
 "image-x-generic" "package-x-generic" "image-x-generic" "package-x-generic"
 "audio-x-generic" "image-x-generic" "image-x-generic" "multipart-x-generic"
 "application-x-generic" "x-content-x-generic" "audio-x-generic"
 "text-x-generic" "text-x-generic" "x-office-spreadsheet" "package-x-generic"
 "video-x-generic" "image-x-generic" "application-x-executable"
 "image-x-generic" "application-x-generic" "text-x-generic" "audio-x-generic"
 "x-office-document" "package-x-generic" "video-x-generic" "audio-x-generic"
 "x-office-document" "text-x-generic" "text-x-generic" "text-x-generic"
 "x-office-document" "x-office-document" "text-x-generic" "x-content-x-generic"
 "application-x-generic" "application-x-generic" "image-x-generic"
 "package-x-generic" "application-x-generic" "x-office-document"
 "audio-x-generic" "x-office-document" "text-x-script" "video-x-generic"
 "application-x-generic" "x-office-spreadsheet" "text-x-generic"
 "package-x-generic" "inode-x-generic" "text-x-generic" "text-x-generic"
 "video-x-generic" "audio-x-generic" "text-x-generic" "x-office-document"
 "text-x-generic" "text-x-generic" "package-x-generic" "application-x-generic"
 "image-x-generic" "font-x-generic" "text-x-generic" "application-x-generic"
 "image-x-generic" "inode-x-generic" "application-x-generic" "text-x-generic"
 "text-x-generic" "x-office-document" "x-office-document" "text-x-generic"
 "x-office-spreadsheet" "package-x-generic" "application-x-generic"
 "package-x-generic" "audio-x-generic" "package-x-generic" "video-x-generic"
 "package-x-generic" "video-x-generic" "font-x-generic" "audio-x-generic"
 "application-x-generic" "image-x-generic" "font-x-generic" "text-x-generic"
 "image-x-generic" "text-x-script" "video-x-generic" "application-x-generic"
 "text-x-generic" "x-office-presentation" "font-x-generic" "video-x-generic"
 "package-x-generic" "image-x-generic" "application-x-generic" "text-x-generic"
 "image-x-generic" "audio-x-generic" "x-office-document" "image-x-generic"
 "text-x-generic" "text-x-generic" "x-office-spreadsheet" "package-x-generic"
 "video-x-generic" "text-x-generic" "image-x-generic" "image-x-generic"
 "image-x-generic" "x-office-document" "text-x-generic" "audio-x-generic"
 "x-office-document" "x-office-document" "font-x-generic" "image-x-generic"
 "x-office-document" "x-content-x-generic" "x-content-x-generic"
 "text-x-generic" "audio-x-generic" "text-x-generic" "image-x-generic"
 "x-office-document" "application-x-executable" "x-office-presentation"
 "multipart-x-generic" "application-x-generic" "x-office-presentation"
 "text-x-script" "text-x-generic" "text-x-generic" "image-x-generic"
 "text-x-script" "video-x-generic" "text-x-generic" "application-x-generic"
 "package-x-generic" "application-x-generic" "application-x-generic"
 "text-x-generic" "application-x-generic" "font-x-generic" "video-x-generic"
 "text-x-generic" "image-x-generic" "x-office-document" "font-x-generic"
 "image-x-generic" "text-x-generic" "video-x-generic" "image-x-generic"
 "text-x-generic" "x-office-presentation" "text-x-generic" "x-office-document"
 "image-x-generic" "application-x-generic" "application-x-generic"
 "package-x-generic" "text-x-generic" "application-x-executable"
 "text-x-generic" "audio-x-generic" "audio-x-generic" "application-x-generic"
 "package-x-generic" "text-x-generic" "application-x-generic" "text-x-generic"
 "application-x-generic" "x-office-spreadsheet" "audio-x-generic"
 "x-office-document" "text-x-generic" "audio-x-generic" "x-office-presentation"
 "x-office-document" "text-x-generic" "text-x-generic" "text-x-generic"
 "x-office-document" "text-x-generic" "text-x-script" "application-x-generic"
 "text-x-generic" "image-x-generic" "x-office-document" "x-office-document"
 "text-x-generic" "text-x-generic" "x-office-spreadsheet" "font-x-generic"
 "audio-x-generic" "x-office-presentation" "x-office-spreadsheet"
 "text-x-generic" "audio-x-generic" "text-x-generic" "package-x-generic"
 "text-x-generic" "text-x-generic" "multipart-x-generic" "image-x-generic"
 "text-x-generic" "image-x-generic" "application-x-executable"
 "video-x-generic" "x-office-document" "x-office-presentation"
 "image-x-generic" "image-x-generic" "image-x-generic" "video-x-generic"
 "application-x-generic" "image-x-generic" "audio-x-generic" "audio-x-generic"
 "text-x-script" "text-x-script" "application-x-generic"
 "x-office-presentation" "x-content-x-generic" "audio-x-generic"
 "audio-x-generic" "font-x-generic" "application-x-generic" "package-x-generic"
 "x-office-document" "audio-x-generic" "text-x-generic" "audio-x-generic"
 "application-x-generic" "application-x-generic" "font-x-generic"
 "text-x-generic" "x-office-spreadsheet" "application-x-generic"
 "video-x-generic" "video-x-generic" "application-x-executable"
 "audio-x-generic" "text-x-generic" "application-x-generic"
 "x-office-presentation" "image-x-generic" "x-office-spreadsheet"
 "x-content-x-generic" "x-content-x-generic" "package-x-generic"
 "package-x-generic" "x-office-document" "package-x-generic"
 "x-office-document" "application-x-generic" "x-office-document"
 "text-x-generic" "text-x-generic" "image-x-generic" "x-office-document"
 "image-x-generic" "x-content-x-generic" "package-x-generic"
 "x-office-spreadsheet" "application-x-executable" "font-x-generic"
 "text-x-generic" "image-x-generic" "application-x-generic" "image-x-generic"
 "application-x-generic" "application-x-generic" "image-x-generic"
 "text-x-generic" "x-office-document" "x-office-presentation" "font-x-generic"
 "audio-x-generic" "audio-x-generic" "image-x-generic" "x-office-document"
 "package-x-generic" "image-x-generic" "image-x-generic" "x-office-document"
 "text-x-generic" "text-x-generic" "package-x-generic" "package-x-generic"
 "x-office-document" "package-x-generic" "audio-x-generic"
 "application-x-generic" "audio-x-generic" "text-x-generic"
 "x-office-spreadsheet" "x-office-presentation" "text-x-generic"
 "application-x-generic" "x-office-spreadsheet" "audio-x-generic"
 "x-content-x-generic" "text-x-generic" "text-x-script" "text-x-generic"
 "x-office-document" "x-content-x-generic" "application-x-generic"
 "text-x-generic" "package-x-generic" "text-x-generic" "text-x-generic"
 "text-x-script" "image-x-generic" "x-office-document" "x-office-document"
 "x-office-document" "video-x-generic" "text-x-generic" "video-x-generic"
 "package-x-generic" "application-x-generic" "image-x-generic"
 "image-x-generic" "image-x-generic" "application-x-generic" "image-x-generic"
 "image-x-generic" "x-office-document" "video-x-generic" "text-x-generic"
 "x-office-presentation" "video-x-generic" "package-x-generic"
 "x-office-document" "application-x-generic" "audio-x-generic"
 "application-x-generic" "text-html" "package-x-generic" "image-x-generic"
 "text-x-generic" "video-x-generic" "x-office-document" "text-x-script"
 "package-x-generic" "application-x-generic" "x-office-document"
 "image-x-generic" "text-html" "x-office-document" "image-x-generic"
 "audio-x-generic" "image-x-generic" "image-x-generic" "image-x-generic"
 "image-x-generic" "video-x-generic" "text-x-generic" "x-office-document"
 "application-x-executable" "text-x-generic" "application-x-generic"
 "text-x-generic" "text-x-generic" "package-x-generic" "x-office-document"
 "image-x-generic" "x-office-document" "x-office-spreadsheet" "image-x-generic"
 "text-x-generic" "application-x-executable" "text-x-generic" "font-x-generic"
 "text-x-script" "text-x-generic" "application-x-generic" "text-x-generic"
 "text-x-generic" "text-x-generic" "text-x-generic" "x-office-presentation"
 "text-html" "x-office-document" "text-x-generic" "application-x-generic"
 "application-x-generic" "application-x-generic" "text-x-generic"
 "application-x-generic" "video-x-generic" "audio-x-generic" "text-x-generic"
 "x-office-spreadsheet" "video-x-generic" "x-office-document"
 "application-x-generic" "text-x-generic" "text-x-generic" "text-x-generic"
 "x-content-x-generic" "package-x-generic" "image-x-generic"
 "x-office-document" "x-office-document" "text-x-generic" "image-x-generic"
 "text-x-generic" "text-x-generic" "application-x-generic" "video-x-generic"
 "application-x-executable" "x-office-document" "text-x-generic"
 "x-office-document" "package-x-generic" "x-content-x-generic"
 "x-office-spreadsheet" "application-x-generic" "image-x-generic"
 "text-x-generic" "text-x-generic" "x-office-spreadsheet" "audio-x-generic"
 "image-x-generic" "text-x-generic" "multipart-x-generic" "image-x-generic"
 "inode-x-generic" "font-x-generic" "x-office-document"
 "application-x-executable" "x-office-document" "audio-x-generic"
 "application-x-executable" "image-x-generic" "image-x-generic"
 "video-x-generic" "x-office-spreadsheet" "x-office-presentation"
 "font-x-generic" "image-x-generic" "x-office-spreadsheet" "text-x-generic"
 "text-x-generic" "audio-x-generic" "x-office-document" "audio-x-generic"
 "application-x-generic" "text-x-generic" "x-office-document"
 "x-office-document" "image-x-generic" "image-x-generic"
 "application-x-generic" "application-x-generic" "text-html" "audio-x-generic"
 "application-x-generic" "application-x-generic" "video-x-generic"
 "image-x-generic" "x-office-document" "application-x-generic"
 "package-x-generic" "text-x-generic" "x-office-spreadsheet"
 "x-office-document" "application-x-generic" "text-html" "package-x-generic"
 "x-office-document" "package-x-generic" "package-x-generic" "image-x-generic"
 "x-office-document" "image-x-generic" "text-html" "multipart-x-generic"
 "package-x-generic" "x-content-x-generic" "x-office-document"
 "application-x-generic" "video-x-generic" "audio-x-generic" "text-x-generic"
 "image-x-generic" "x-office-document" "image-x-generic"
 "application-x-generic" "package-x-generic" "inode-x-generic" "text-x-generic"
 "image-x-generic" "multipart-x-generic" "image-x-generic" "video-x-generic"
 "image-x-generic" "text-x-generic" "text-x-generic" "audio-x-generic"
 "text-x-generic" "image-x-generic" "x-office-spreadsheet" "image-x-generic"
 "application-x-generic" "application-x-generic" "application-x-generic"
 "font-x-generic" "audio-x-generic" "x-office-document" "video-x-generic"
 "application-x-generic" "text-html" "application-x-generic"
 "application-x-generic" "x-office-document" "application-x-generic"
 "image-x-generic" "image-x-generic" "image-x-generic" "image-x-generic"
 "application-x-generic" "x-content-x-generic" "application-x-generic"
 "inode-x-generic" "image-x-generic" "text-x-generic" "text-x-generic"
 "package-x-generic" "text-x-generic" "audio-x-generic" "x-office-spreadsheet"
 "package-x-generic" "x-office-presentation" "text-x-generic" "text-x-generic"
 "text-x-generic" "image-x-generic" "text-x-generic" "audio-x-generic"
 "application-x-generic" "application-x-generic" "audio-x-generic"
 "text-x-generic" "application-x-generic" "application-x-generic"
 "text-x-generic" "text-x-script" "audio-x-generic" "image-x-generic"
 "audio-x-generic" "image-x-generic" "text-x-generic" "application-x-generic"
 "x-office-spreadsheet" "application-x-generic" "text-x-generic"
 "x-office-presentation" "x-office-document" "application-x-generic"
 "application-x-generic" "x-office-presentation" "image-x-generic" "text-html"
 "x-office-document" "package-x-generic" "multipart-x-generic"
 "package-x-generic" "text-x-generic" "x-office-spreadsheet"
 "x-office-document" "text-x-generic")
             (mapcar #'g-content-type-get-generic-icon-name
                     (g-content-types-get-registered)))))

;;;   g_content_type_can_be_executable
;;;   g_content_type_from_mime_type
;;;   g_content_type_guess
;;;   g_content_type_guess_for_tree

;;;   g_content_types_get_registered

(test g-content-types-get-registered
  (is (equal '("image/cgm" "video/webm" "application/x-xpinstall" "audio/vnd.dts.hd"
 "application/x-gz-font-linux-psf" "application/vnd.sun.xml.draw"
 "video/x-javafx" "application/x-anjuta-project-template" "application/x-hwt"
 "video/x-matroska" "application/x-font-tex" "application/x-hwp"
 "application/vnd.oasis.opendocument.chart-template" "application/x-cbz"
 "application/x-stuffit" "application/vnd.oasis.opendocument.graphics-flat-xml"
 "application/x-abiword" "application/x-cbt" "text/sgml" "application/x-cbr"
 "application/x-wwf" "text/x-subviewer" "video/x-flv" "text/enriched"
 "application/sieve" "application/rtf" "application/andrew-inset"
 "application/pkix-crl" "text/x-svsrc"
 "application/vnd.sun.xml.writer.template" "application/x-smaf"
 "application/x-sc" "audio/x-gsm" "application/x-tarz" "application/x-spss-por"
 "image/x-olympus-orf" "application/vnd.oasis.opendocument.graphics-template"
 "audio/flac" "message/partial" "application/pgp-signature"
 "application/vnd.scribus" "text/vnd.wap.wml" "text/richtext"
 "application/x-shellscript" "text/x-txt2tags" "application/x-rar"
 "text/x-lilypond" "image/vnd.adobe.photoshop" "application/x-class-file"
 "audio/x-riff" "application/x-gettext-translation" "text/x-haskell"
 "image/x-xcursor" "application/x-graphite" "application/x-navi-animation"
 "application/x-dc-rom" "application/mathml+xml" "inode/mount-point"
 "x-content/audio-dvd" "application/vnd.stardivision.chart"
 "application/x-mswrite" "application/x-zoo" "model/vrml"
 "image/svg+xml-compressed" "image/x-portable-anymap" "image/x-icns"
 "application/x-netshow-channel" "image/x-wmf" "application/x-cb7"
 "application/smil" "application/x-bzpdf" "image/x-xfig" "application/x-qw"
 "text/x-go" "application/x-snes-rom" "x-content/audio-player"
 "application/xml-external-parsed-entity" "application/x-lzop" "image/x-fpx"
 "text/x-nfo" "text/x-cobol" "application/prs.plucker" "text/cache-manifest"
 "application/x-font-vfont" "application/x-bittorrent"
 "x-content/unix-software" "image/vnd.ms-modi" "audio/webm"
 "application/x-kivio" "application/x-pw" "application/x-tzo"
 "application/vnd.google-earth.kmz"
 "application/vnd.openxmlformats-officedocument.presentationml.template"
 "application/x-mif" "multipart/digest" "x-content/video-dvd"
 "application/x-apple-diskimage" "application/x-ace"
 "application/x-font-libgrx" "image/x-macpaint" "image/x-sony-srf"
 "text/vnd.trolltech.linguist" "text/x-ocl"
 "application/vnd.oasis.opendocument.image" "message/delivery-status"
 "application/x-planperfect" "message/external-body" "application/x-t602"
 "image/tiff" "inode/socket" "image/x-kodak-kdc"
 "application/vnd.ms-excel.addin.macroEnabled.12" "audio/x-xmf" "audio/annodex"
 "text/x-eiffel" "text/x-pascal" "application/pgp-encrypted"
 "application/x-shockwave-flash" "application/octet-stream" "video/mpeg"
 "text/x-makefile" "application/vnd.oasis.opendocument.text"
 "application/vnd.emusic-emusic_package" "audio/x-wavpack"
 "application/x-bzip-compressed-tar" "audio/vnd.rn-realaudio" "text/x-iptables"
 "application/x-cdrdao-toc" "multipart/x-mixed-replace" "video/x-ms-asf"
 "application/vnd.sun.xml.draw.template" "text/x-vhdl" "image/x-eps"
 "application/x-kformula" "image/x-xwindowdump"
 "application/vnd.openofficeorg.extension" "image/vnd.microsoft.icon"
 "application/x-lzma" "image/vnd.wap.wbmp" "application/x-7z-compressed"
 "audio/x-tta" "image/x-xpixmap" "image/x-sony-sr2" "multipart/signed"
 "application/x-freefilesync-real" "x-content/video-bluray" "audio/x-musepack"
 "text/x-scala" "text/x-patch" "application/vnd.ms-excel" "application/x-pak"
 "video/x-theora+ogg" "image/x-applix-graphics" "application/x-gba-rom"
 "image/x-msod" "application/x-anjuta" "text/x-svhdr" "audio/x-voc"
 "application/x-glade" "application/x-ksysv-package" "video/x-anim"
 "audio/x-speex" "application/vnd.ms-word.document.macroEnabled.12"
 "application/xslt+xml" "text/x-xmi" "text/vnd.wap.wmlscript"
 "application/vnd.oasis.opendocument.formula"
 "application/vnd.stardivision.writer" "text/x-rpm-spec"
 "x-content/image-picturecd" "application/x-kexiproject-sqlite3"
 "application/x-kexiproject-sqlite2" "image/x-portable-pixmap"
 "application/x-lhz" "application/x-mswinurl"
 "application/vnd.oasis.opendocument.formula-template" "audio/x-ms-wma"
 "application/mathematica" "application/x-java-jnlp-file" "application/mxf"
 "application/x-freefilesync-db"
 "application/vnd.openxmlformats-officedocument.spreadsheetml.template"
 "application/x-chess-pgn" "application/x-ustar" "inode/chardevice"
 "text/x-readme" "text/x-c++src" "video/isivideo" "audio/x-stm" "text/x-apport"
 "application/x-fluid" "application/pkcs10" "text/x-erlang" "application/x-lha"
 "application/x-trig" "application/x-wpg" "application/x-font-speedo"
 "text/x-uri" "application/x-mimearchive" "image/x-portable-bitmap"
 "inode/blockdevice" "application/vnd.android.package-archive" "text/x-ldif"
 "application/x-yaml" "application/x-frame" "application/vnd.ms-works"
 "text/x-ocaml" "application/x-kchart" "application/vnd.symbian.install"
 "application/vnd.ms-powerpoint.template.macroenabled.12"
 "application/x-archive" "audio/x-matroska" "application/x-bzip" "video/x-nsv"
 "application/x-source-rpm" "video/annodex" "application/x-font-afm"
 "audio/mpeg" "application/x-e-theme" "image/x-nikon-nef"
 "application/x-font-bdf" "text/x-csharp" "image/x-emf" "application/x-m4"
 "video/vivo" "application/x-note" "application/xml-dtd"
 "application/vnd.oasis.opendocument.presentation-flat-xml"
 "application/x-font-sunos-news" "application/x-quicktime-media-link"
 "application/x-lzip" "image/x-photo-cd" "application/x-spss-sav"
 "text/x-objcsrc" "image/openraster" "audio/vnd.dts" "application/x-bzdvi"
 "image/jp2" "text/x-mpsub" "application/x-nautilus-link" "application/x-siag"
 "application/x-lrzip-compressed-tar" "video/3gpp2" "text/vtt"
 "image/x-sun-raster" "image/x-sony-arw" "application/dicom"
 "application/x-amipro" "text/x-adasrc" "audio/x-s3m" "application/x-dvi"
 "application/x-gnuplot" "application/font-woff" "image/x-xbitmap"
 "application/x-gzpostscript" "x-content/image-dcf" "x-content/audio-cdda"
 "text/x-credits" "audio/x-speex+ogg" "text/html" "image/x-xcf"
 "application/x-aportisdoc" "application/x-pef-executable"
 "application/vnd.stardivision.impress" "multipart/encrypted"
 "application/vnd.ms-word"
 "application/vnd.oasis.opendocument.presentation-template"
 "application/x-shared-library-la" "application/x-wais-source" "text/x-dsl"
 "image/x-minolta-mrw" "application/x-markaby" "video/vnd.mpegurl"
 "text/x-bibtex" "application/gnunet-directory" "application/x-shar"
 "application/x-homebank" "application/x-pkcs7-certificates" "text/x-ssa"
 "application/x-java-jce-keystore" "application/x-font-framemaker"
 "video/x-flic" "message/x-gnu-rmail" "application/vnd.hp-pcl"
 "application/vnd.ms-word.template.macroEnabled.12" "application/x-font-pcf"
 "application/x-karbon" "text/x-vala" "video/x-ogm+ogg" "image/g3fax"
 "text/x-scheme" "application/vnd.oasis.opendocument.presentation" "text/htmlh"
 "application/x-designer" "application/x-killustrator" "application/x-ms-wim"
 "application/x-cd-image" "application/x-cpio-compressed" "text/x-c++hdr"
 "application/x-n64-rom" "text/x-sql" "audio/x-aiff" "audio/x-it"
 "application/vnd.ms-tnef" "application/x-sv4cpio" "application/x-cue"
 "application/x-kexi-connectiondata" "text/rfc822-headers"
 "application/pkix-pkipath"
 "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
 "audio/x-aifc" "application/x-gzpdf" "application/x-cisco-vpn-settings"
 "audio/x-amzxml" "application/vnd.ms-powerpoint.addin.macroEnabled.12"
 "application/x-gtk-builder" "text/x-troff-ms" "text/x-emacs-lisp"
 "text/x-java" "application/epub+zip" "text/x-texinfo" "application/javascript"
 "application/gml+xml" "text/x-troff-mm" "image/fits"
 "application/vnd.ms-htmlhelp" "application/x-xzpdf" "application/x-sami"
 "text/x-troff-me" "application/x-applix-spreadsheet"
 "application/x-font-tex-tfm" "audio/x-psflib" "application/vnd.ms-powerpoint"
 "application/x-quattropro" "text/x-modelica" "application/x-shorten"
 "application/relax-ng-compact-syntax" "application/x-bcpio"
 "application/x-subrip" "application/x-ccmx" "multipart/report"
 "application/vnd.corel-draw" "text/x-python" "image/x-panasonic-raw2"
 "application/x-genesis-rom" "application/sdp" "application/x-jbuilder-project"
 "application/vnd.sun.xml.impress.template" "image/x-tga" "image/x-lws"
 "image/x-dib" "video/dv" "application/vnd.apple.mpegurl" "image/x-lwo"
 "audio/x-ms-asx" "audio/x-psf" "application/x-csh" "application/x-awk"
 "application/vnd.google-earth.kml+xml"
 "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" "x-content/blank-cd"
 "audio/x-wavpack-correction" "audio/prs.sid" "application/x-tex-pk"
 "application/pkcs8" "application/x-compressed-tar" "application/vnd.visio"
 "audio/x-iriver-pla" "text/x-idl" "audio/x-adpcm" "application/x-spkac"
 "application/x-iff" "application/x-font-linux-psf" "text/troff"
 "application/x-gnucash" "application/rdf+xml" "video/mp4" "video/x-mng"
 "application/x-ms-dos-executable" "audio/x-vorbis+ogg" "text/spreadsheet"
 "application/x-core"
 "application/vnd.openxmlformats-officedocument.presentationml.presentation"
 "image/x-bzeps" "application/vnd.ms-excel.sheet.macroEnabled.12"
 "x-content/win32-software" "x-content/blank-bd" "application/mac-binhex40"
 "application/vnd.ms-cab-compressed" "application/msword"
 "application/x-lzma-compressed-tar" "application/x-pocket-word"
 "application/x-nzb" "application/x-kword" "text/x-verilog" "text/x-uil"
 "image/x-portable-graymap" "application/postscript" "image/x-sgi"
 "x-content/video-vcd" "application/x-lrzip"
 "application/vnd.ms-excel.sheet.binary.macroEnabled.12"
 "application/x-sms-rom" "application/x-font-ttx" "text/x-markdown"
 "application/x-dia-diagram" "application/x-spkac+base64"
 "image/vnd.rn-realpix" "application/x-freefilesync-ffs"
 "application/vnd.ms-word.document.macroenabled.12" "image/fax-g3"
 "text/x-dsrc" "application/vnd.stardivision.math"
 "application/vnd.ms-powerpoint.presentation.macroEnabled.12"
 "application/x-font-ttf" "audio/mp4" "audio/mp2" "application/vnd.hp-hpgl"
 "application/x-applix-word" "application/x-theme" "application/x-kpovmodeler"
 "image/x-skencil" "application/vnd.mozilla.xul+xml" "application/x-go-sgf"
 "text/x-gettext-translation" "application/x-java-archive" "application/x-rpm"
 "application/vnd.lotus-wordpro" "application/gzip" "audio/x-ape"
 "application/x-brasero" "audio/x-wav" "text/x-ms-regedit"
 "application/x-kspread" "application/x-kpresenter" "text/x-setext"
 "application/pkcs12+pem" "application/vnd.ms-excel.template.macroEnabled.12"
 "audio/AMR" "x-content/software" "application/x-profile" "application/x-perl"
 "application/x-gmc-link" "application/vnd.oasis.opendocument.database"
 "x-content/ebook-reader" "application/vnd.tcpdump.pcap" "text/csv"
 "application/x-windows-themepack" "application/x-ica" "text/css"
 "application/x-asp" "image/x-rgb" "application/x-ole-storage"
 "application/x-bzpostscript" "application/x-qtiplot" "video/ogg"
 "application/x-xliff" "application/vnd.ms-wpl" "application/x-java-pack200"
 "application/metalink+xml" "image/x-dds" "image/x-canon-crw"
 "image/x-kodak-dcr" "application/x-zerosize" "image/x-dcraw" "image/dpx"
 "application/vnd.oasis.opendocument.text-template" "application/annodex"
 "text/plain"
 "application/vnd.openxmlformats-officedocument.presentationml.slide"
 "video/x-msvideo" "application/x-slp" "application/x-hdf" "application/ram"
 "audio/x-mpegurl" "application/metalink4+xml" "application/x-xbel"
 "application/x-arj" "image/x-pict" "application/pgp-keys" "application/ogg"
 "application/x-gzdvi" "application/x-ruby" "application/x-arc"
 "application/x-trash" "application/vnd.wordperfect" "application/x-blender"
 "text/x-opml+xml"
 "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
 "image/x-fuji-raf" "audio/ogg" "image/ief" "image/x-compressed-xcf"
 "image/x-pentax-pef" "image/gif" "video/quicktime" "text/x-uuencode"
 "application/x-lyx" "application/x-executable" "text/x-qml"
 "application/pkcs7-mime+pem" "text/x-changelog" "text/x-mup"
 "application/x-macbinary" "application/pdf" "image/jpeg"
 "application/vnd.oasis.opendocument.text-flat-xml" "application/x-gnumeric"
 "image/x-canon-cr2" "message/news" "application/x-gameboy-rom"
 "text/x-literate-haskell" "application/x-font-type1" "application/ecmascript"
 "text/vnd.rn-realtext" "application/vnd.ms-word.template.macroenabled.12"
 "text/x-reject" "text/x-cmake" "application/x-troff-man"
 "application/x-desktop"
 "application/vnd.openxmlformats-officedocument.presentationml.slideshow"
 "application/atom+xml" "application/x-docbook+xml"
 "application/pkcs7-signature" "application/x-sharedlib" "application/winhlp"
 "application/x-pem-file" "text/x-matlab" "application/x-pkcs12"
 "video/x-sgi-movie" "audio/x-m4b" "text/x-tex"
 "application/vnd.sun.xml.calc.template" "application/x-matroska"
 "application/vnd.oasis.opendocument.text-master"
 "application/x-fictionbook+xml" "text/x-authors"
 "text/vnd.sun.j2me.app-descriptor" "text/x-microdvd" "x-content/video-hddvd"
 "application/x-cpio" "application/x-kontour" "application/vnd.ms-access"
 "application/vnd.sun.xml.math" "text/calendar" "application/x-egon"
 "text/x-apt-sources-list" "text/x-csrc" "application/pkcs10+pem"
 "video/vnd.rn-realvideo" "application/x-msx-rom" "application/oda"
 "text/x-ooc" "text/vnd.graphviz" "application/x-sv4crc" "x-content/video-svcd"
 "application/x-oleo" "application/pkcs8+pem"
 "application/vnd.oasis.opendocument.graphics" "text/x-lua"
 "text/x-google-video-pointer" "application/vnd.oasis.opendocument.spreadsheet"
 "audio/midi" "image/x-cmu-raster" "application/pkcs7-mime"
 "multipart/appledouble" "image/vnd.dxf" "inode/fifo" "application/x-font-dos"
 "application/x-gedcom" "application/x-nes-rom" "application/x-toutdoux"
 "audio/ac3" "application/x-nintendo-ds-rom" "image/vnd.djvu"
 "image/x-panasonic-raw" "video/mp2t" "application/vnd.lotus-1-2-3"
 "application/vnd.sun.xml.impress" "application/x-tex-gf"
 "application/vnd.stardivision.draw" "application/vnd.stardivision.calc"
 "text/x-install" "application/mbox" "audio/aac" "application/x-object"
 "application/xspf+xml" "application/x-gnome-saved-search" "text/x-tcl"
 "application/vnd.sun.xml.writer" "application/x-netcdf" "image/x-kodak-k25"
 "image/vnd.dwg" "application/x-sqlite3" "application/x-sqlite2"
 "application/x-mozilla-bookmarks" "audio/x-mod"
 "application/x-python-bytecode" "application/x-msi"
 "application/vnd.rn-realmedia" "application/illustrator"
 "application/vnd.sun.xml.writer.global" "application/vnd.iccprofile"
 "application/x-alz" "text/x-xslfo"
 "application/vnd.oasis.opendocument.spreadsheet-flat-xml"
 "application/x-gtktalog" "application/x-java-keystore" "application/rss+xml"
 "application/x-compress"
 "application/vnd.openxmlformats-officedocument.wordprocessingml.template"
 "application/x-xz-compressed-tar" "application/zip" "image/rle"
 "application/msword-template" "image/x-pcx" "application/xml"
 "multipart/mixed" "application/x-xz" "x-content/blank-hddvd"
 "application/x-krita" "application/x-kexiproject-shortcut" "video/3gpp"
 "audio/x-mo3" "text/x-dcl" "image/bmp" "application/x-kword-crypt"
 "image/x-ilbm" "application/x-freefilesync-batch" "application/x-deb"
 "inode/directory" "text/x-gettext-translation-template" "image/x-gzeps"
 "multipart/alternative" "application/x-dia-shape" "video/x-ms-wmv"
 "image/x-quicktime" "text/x-fortran" "text/x-moc" "audio/x-scpls" "text/x-mof"
 "image/x-apple-ios-png"
 "application/vnd.oasis.opendocument.spreadsheet-template" "image/x-3ds"
 "application/vnd.ms-powerpoint.presentation.macroenabled.12"
 "application/x-anjuta-compressed-project-template"
 "application/x-ipod-firmware" "application/x-font-otf" "audio/x-flac+ogg"
 "application/x-mobipocket-ebook" "video/wavelet" "application/x-mps"
 "application/vnd.oasis.opendocument.text-web"
 "application/vnd.stardivision.mail"
 "application/vnd.ms-excel.template.macroenabled.12" "application/oxps"
 "application/x-pem-key" "image/x-sigma-x3f" "image/x-exr" "image/png"
 "image/x-jng" "application/pkix-cert+pem" "x-content/blank-dvd"
 "application/pkix-crl+pem" "inode/symlink" "image/x-win-bitmap" "text/x-chdr"
 "application/x-it87" "application/x-tar" "text/x-copying" "audio/AMR-WB"
 "application/vnd.oasis.opendocument.chart" "application/x-par2"
 "application/vnd.ms-powerpoint.template.macroEnabled.12"
 "application/x-x509-ca-cert" "message/rfc822" "text/tab-separated-values"
 "application/x-ufraw" "application/x-troff-man-compressed" "audio/x-xm"
 "application/x-java" "application/vnd.palm" "audio/x-xi" "text/x-log"
 "application/x-keepass2" "application/vnd.ms-excel.sheet.macroenabled.12"
 "text/x-iMelody" "application/x-php" "audio/basic" "image/svg+xml"
 "audio/x-minipsf" "image/x-niff" "text/vcard" "application/pkix-cert"
 "application/x-kspread-crypt" "application/vnd.sun.xml.base" "text/xmcd"
 "application/x-magicpoint" "application/x-dbf"
 "application/vnd.ms-excel.sheet.binary.macroenabled.12" "application/x-gdbm"
 "application/vnd.ms-powerpoint.slide.macroEnabled.12" "image/x-adobe-dng"
 "application/xhtml+xml" "application/x-tgif" "x-epoc/x-sisx-app"
 "multipart/related" "application/x-dar" "text/x-mrml"
 "application/vnd.sun.xml.calc" "application/x-kugar"
 "message/disposition-notification")
 (g-content-types-get-registered))))

