\input texinfo
@c -*-texinfo-*-

@setfilename  gtk-tutorial.info

@c %**start of header
@synindex vr fn
@synindex cp fn
@settitle GTK+ 3 Tutorial for Lisp
@c %**end of header

@setchapternewpage odd
@ifinfo
This is a Texinfo GTK+ 3 Tutorial for Lisp

Copyright (C) 2012, 2013 Dieter Kaiser

@format
INFO-DIR-SECTION Math
START-INFO-DIR-ENTRY
* Tutorial: (tutorial).     A GTK+ 3 Tutorial for Lisp.
END-INFO-DIR-ENTRY
@end format
@end ifinfo

@ifinfo
@macro var {expr}
<\expr\>
@end macro
@end ifinfo

@c Links to the external GTK+ API documenation
@include gtk-links.texi

@titlepage
@sp 10
@comment The title is printed in a large font.
@center @titlefont{GTK+ 3 Tutorial for Lisp}
@sp 2
@center @copyright{} Dieter Kaiser
@sp 1
@center Version 1.0
@page
@vskip 0pt plus 1filll
@end titlepage

@summarycontents
@contents

@ifnottex
@node Top, Introduction, (dir), (dir)
@top
@end ifnottex

@menu
* Introduction::                     Introduction to GTK+ 3 for Lisp
* Getting Started::                  First steps
* Packing Widgets::                  Packing widgets into boxes
* Button Widgets::                   All about buttons
* Display Widgets::                  Labels, Progress, Status, and Info Bars
* Adjustments::
* Range Widgets::
* Layout Widgets::
* Multiline Text Editor::
* Tree and List Widgets::
* Dialogs::                          General, Message and About Dialogs
* Selecting Colors Files and Fonts:: Choosing Colors, Files and Fonts
* Miscellaneous Widgets::
* Menus and Toolbars::               Creation of Menus and Toolbars
* Application Support::
* GTK+ and Cairo::                   Using Cairo for drawing in GTK+

Appendix
* Tables::
* Figures::
* Examples::
* Licenses::

Index
* Function and Variable Index:: Index.

 --- The Detailed Node Listing ---

Introduction
* Introduction::

Getting Started
* Getting Started::
* Installation::
* A Simple Window::
* More about the Lisp binding to GTK+::
* Hello World in GTK+::
* Introduction to Signals and Callbacks::
* An Upgraded Hello World::
* Drawing::

Packing Widgets
* Packing Widgets::
* Packing Boxes::
* Details of Boxes::
* Packing Using Tables::
* Table Packing Example::
* Packing Using Grids::
* Grid Packing Examples::

Button Widgets
* Button Widgets::
* Normal Buttons::
* Toggle Buttons::
* Check Buttons::
* Radio Buttons::
* Link Buttons::
* Switches::

Display Widgets
* Labels::
* Images::
* Progress Bars::
* Statusbars::
* Info Bars::

Adjustments
* Adjustments::
* Introduction to Adjustments::
* Creating an Adjustment::
* Using Adjustments the Easy Way::
* Adjustment Internals::

Range Widgets
* Range Widgets::
* Introduction to Range Widgets::
* Scrollbar Widgets::
* Scale Widgets::
* Common Range Functions::
* Example Range Widgets::

Layout Widgets
* Alignment Widget::
* Fixed Container::
* Layout Container::
* Frames::
* Aspect Frames::
* Paned Window Widgets::
* Viewports::
* Scrolled Windows::
* Button Boxes::
* Toolbar::
* Notebook::

Multiline Text Editor
* Multiline Text Editor::
* Text Widget Overview::
* Simple Multiline Text Widget::
* Formated Text in Text Widget::
* Cut Copy and Paste::
* Searching::
* Examing and Modify Text::
* Images and Widgets::
* Buffer and Window Coordinates::
* Final Notes::

Tree and List Widgets
* Tree and List Widgets::
* Overview::
* GtkListStore and GtkTreeStore::
* Creating a Tree View::
* Mapping Data to the Screen::
* Selections Double-Clicks and Context Menus::
* Sorting::
* Editable Cells::
* Miscellaneous::
* Drag and Drop::
* Writing Custom Models::
* Writing Custom Cell Renderers::

Dialogs
* Dialogs::
* General Dialog::
* Message Dialog::
* About Dialog::

Selecting Colors, Files, and Fonts
* Selecting Colors Files and Fonts::
* Selecting Colors::
* Selecting Files::
* Selecting Fonts::

Miscellaneous Widgets
* Miscellaneous Widgets::
* Arrows::
* Calendar::
* Event Box::
* Text Entries::
* Spin Buttons::
* Combo Box::
* General Combo Box::
* Combo Box Text::

Menus and Toolbars
* Menus and Toolbars::
* Menus::
* Principles of Menus::
* Creating Menus by Hand::
* Pop-Up Menus for Widgets::
* Toolbars::
* GtkUIManager::

GTK+ and Cairo
* GTK+ and Cairo::
* Cairo Drawing Model::
* Drawing with Cairo::
* Understanding Text::
* Working with Transforms::
* Where to Go Next::
* Tips and Tricks::
* Writing a Widget Using Cairo and GTK::

Application Support
* Application Class::
* Application Window::
* Simple Application::
@end menu

@node Introduction, Getting Started, Top, Top
@chapter Introduction
@include gtk-introduction.texi

@node Getting Started, Packing Widgets, Introduction, Top
@chapter Getting Started
@include gtk-getting-started.texi

@node Packing Widgets, Button Widgets, Getting Started, Top
@chapter Packing Widgets
@include gtk-packing-widgets.texi

@node Button Widgets, Display Widgets, Packing Widgets, Top
@chapter Button Widgets
@include gtk-button-widget.texi

@node Display Widgets, Adjustments, Button Widgets, Top
@chapter Display Widgets
@include gtk-display-widgets.texi

@node Adjustments, Range Widgets, Display Widgets, Top
@chapter Adjustments
@include gtk-adjustments.texi

@node Range Widgets, Layout Widgets, Adjustments, Top
@chapter Range Widgets
@include gtk-range-widgets.texi

@node Layout Widgets, Multiline Text Editor, Range Widgets, Top
@chapter Layout Widgets
@include gtk-container-widgets.texi

@node Multiline Text Editor, Tree and List Widgets, Layout Widgets, Top
@chapter Multiline Text Editor
@include gtk-text-view.texi

@node Tree and List Widgets, Dialogs, Multiline Text Editor, Top
@chapter Tree and List Widgets
@include gtk-tree-and-list-widget.texi

@node Dialogs, Selection Colors Files and Fonts, Tree and List Widgets, Top
@chapter Dialogs
@include gtk-dialogs.texi

@node Selecting Colors Files and Fonts, Miscellaneous Widgets, Dialogs, Top
@chapter Selecting Colors, Files and Fonts
@include gtk-selectors.texi

@node Miscellaneous Widgets, Menus and Toolbars, Selecting Colors Files and Fonts, Top
@chapter Miscellaneous Widgets
@include gtk-misc-widgets.texi

@node Menus and Toolbars, Application Support, Miscellaneous Widgets, Top
@chapter Menus and Toolbars
@include gtk-menu-widget.texi

@node Application Support, Reference of Widgets, Menus and Toolbars, Top
@chapter Application Support
@include gtk-application.texi

@node GTK+ and Cairo, Tables, Application Support, Top
@chapter GTK+ and Cairo
@include gtk-cairo.texi

@node Tables, Figures, GTK+ and Cairo, Top
@appendix Tables
@listoffloats Table

@node Figures, Examples, Tables, Top
@appendix Figures
@listoffloats Figure

@node Examples, Function and Variable Index, Figures, Top
@appendix Examples
@listoffloats Example

@node Function and Variable Index, Licenses, Menu Widget, Top
@appendix Function and Variable Index
@printindex fn

@node Licenses, , Function and Variable Index, Top
@appendix Licenses
@include gtk-licenses.texi

@bye

